name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16]
      fail-fast: false

    name: 'Build&Test: node-${{ matrix.node_version }}, ${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Versions
        run: yarn versions

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  lint:
    runs-on: ubuntu-latest
    name: 'Lint: node-16, ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Prepare
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Lint
        run: yarn lint
